apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assure-api-db-pvc
  namespace: preprod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
